# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subtui < Formula
  desc "A Subsonic TUI Client"
  homepage "https://github.com/MattiaPun/SubTUI"
  version "2.5.1"
  license "MIT"

  depends_on "mpv"

  on_macos do
    on_intel do
      url "https://github.com/MattiaPun/SubTUI/releases/download/v2.5.1/SubTUI_darwin_amd64.tar.gz"
      sha256 "1e9f5c784e437520fd3fc1083f975f45e1a5f3475f7f6cd181db201fbb350693"

      def install
        bin.install "subtui"
      end
    end
    on_arm do
      url "https://github.com/MattiaPun/SubTUI/releases/download/v2.5.1/SubTUI_darwin_arm64.tar.gz"
      sha256 "c5fe0d9e2f675b41dca2b4606595f20f775ebd9f3754ef0fcdf7732084f8190c"

      def install
        bin.install "subtui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MattiaPun/SubTUI/releases/download/v2.5.1/SubTUI_linux_amd64.tar.gz"
        sha256 "31d26dd10c671892d70ec824c51f24509ca606d783eab589d7cd1cae7d4c47fa"

        def install
          bin.install "subtui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MattiaPun/SubTUI/releases/download/v2.5.1/SubTUI_linux_arm64.tar.gz"
        sha256 "cadbd8940555616392d70b5340ad99252b451c494dd173911c6706fbe57e93ec"

        def install
          bin.install "subtui"
        end
      end
    end
  end
end
